name: foss4g
channels:
  - ioam
  - bokeh
  - conda-forge
  - damianavila82
  - defaults
dependencies:
  - python=3
  - notebook
  - holoviews
  - geoviews
  - pandas
  - xarray
  - datashader
  - paramnb
  - rise
  - jupyter_dashboards
  - fastparquet
  - python-snappy
  - parambokeh
